# Generated by Django 3.0.4 on 2020-03-21 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_remove_rate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='data_publish',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
