# Generated by Django 3.0.4 on 2020-03-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_auto_20200321_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='User_Rate',
        ),
    ]
